[main]
dir = "/tmp/introduction_to_cryptography"
username = "username"
password = "password"
course = "Introduction to Cryptography (Summer 2024)"
folders = [
  "Recordings",
  "Annotated Slides",
  "Exercises",
  [
    "Material & Solutions for the Exercises",
    [
      "Exercise-02",
    ],
  ],
  "Slides",
]
